### ISSUE TITLE
can I custom the under-construction page?

### ISSUE THREAD

**Issue by liucf** [jrl05k/laravel-under-construction#2]
it will redirect to under-construction page.

but can i custom that page?

Thanks

**Comment by f-rostami** [comment]
no option defined for these purpose (or at least i can't find it) but if you want to change it  default view you can go to: 
`\vendor\jrl05k\laravel-under-construction\src\UnderConstructionController.php`
and change the index function and render any "view" you want.

**Comment by jrl05k** [comment]
according to documentation for laravel 5.6, 
you can override package views:  https://laravel.com/docs/5.6/packages#views

so you could try creating view directory: resources/views/jrl05k/lararvel-under-construction
and put your views there (under_construction.blade.php and under_construction_login.blade.php)

but I haven't tried it yet though...

**Comment by jrl05k** [comment]
You can override views by creating your custom views in paths: 

resources/views/vendor/underconstruction/under_construction.blade.php
resources/views/vendor/underconstruction/under_construction_login.blade.php
